<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ETBMS PO</name>
   <tag></tag>
   <elementGuidId>80a40a92-4d39-447d-bfe1-fc6e8e994959</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#etbmsPO</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='loanDetailsTable']/tr/td[2]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;etbmsPO&quot;)[count(. | //input[@id = 'etbmsPO' and @type = 'number' and @ref_element = 'Object Repository/Page_TELESCOOP - PLDT Employees Multi-Purpo_3f52d5/iframe']) = count(//input[@id = 'etbmsPO' and @type = 'number' and @ref_element = 'Object Repository/Page_TELESCOOP - PLDT Employees Multi-Purpo_3f52d5/iframe'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>etbmsPO</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;etbmsPO&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='etbmsPO']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='loanDetailsTable']/tr/td[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
   </webElementXpaths>
</WebElementEntity>
